apiVersion: v2
name: kafkaui
description: A Helm chart for KafkaUI - web UI for Apache Kafka
type: application
version: 0.13.1
appVersion: "0.13.1"
home: https://github.com/Smyrcu/KafkaUI
sources:
  - https://github.com/Smyrcu/KafkaUI
maintainers:
  - name: Smyrcu
