replicaCount: 1

image:
  repository: kafkaui
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

podSecurityContext:
  runAsNonRoot: true
  fsGroup: 65534

securityContext:
  runAsUser: 65534
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

env: []
envFrom: []

podAnnotations: {}

extraVolumes: []
extraVolumeMounts: []

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: kafkaui.local
  tls: []

resources: {}

persistence:
  enabled: false
  size: 100Mi
  storageClass: ""

config: |
  server:
    port: 8080
  clusters:
    - name: local
      bootstrap-servers: kafka:9092
